### ISSUE TITLE
Turtle doesn't move after refuel

### ISSUE THREAD

**Issue by BennyCodet** [Miki-Tellurium/TurtleChargingStation#2]
The turtle doesn't continue the program after refueling. Is this a bug or do I have to configure sth? Playing on 1.20.1 (Direwolf20)

**Comment by Miki-Tellurium** [comment]
What version of the modpack are you using?

**Comment by Miki-Tellurium** [comment]
I don't notice anything wrong when charging turtles during a program execution in the latest version of DireWolf20 (1.21.1). Can you provide more detail?

**Comment by BennyCodet** [comment]
Thanks for the reply. I'm playing on Direwolf20 1.12.1 (MC Version 1.20.1)
https://www.feed-the-beast.com/modpacks/119-ftb-presents-direwolf20-120?tab=about

I'm running the excavate program and if the turtle returns with the "out of fuel" message, it get refueled but it does not continue the programm after refueling

**Comment by BennyCodet** [comment]
But if you can't recreate I think I found a workaround in increasing the conversion rate so it refuels faster while returning the items. So it never runs out of fuel when it get started with enough fuel

**Comment by Miki-Tellurium** [comment]
I think that is just the normal behavior of the excavate program, it stops if the turtle runs out of fuel and the charging station is not fast enough to recharge it. So it's not an issue, its the intended behavior of the turtle.
