### ISSUE TITLE
Is there no recipe for "Turtle charging station"?

### ISSUE THREAD

**Issue by LeonardoCT** [Miki-Tellurium/TurtleChargingStation#3]
Hello, i've installed the mod and tested it in creative, but i noticed it has no recipe for the block "Turtle charging station" but the dynamo does is it a problem with JEI or the block has no recipe?

**Comment by Miki-Tellurium** [comment]
What version of the mod are you using? Have you installed other mods like mekanism, thermal expansion or powah?

**Comment by LeonardoCT** [comment]
Hello, thank you for the fast reply, i'm using "turtlechargingstation-1.4.1-1.20" downloaded form the official source:
https://modrinth.com/mod/turtle-charging-station/versions?g=1.20.1
I have both thermal expansion and powah
I'm running on Minecraft 1.20.1 with forge 47.2.20

**Comment by Miki-Tellurium** [comment]
There was a problem with the conditional recipe when other mod are installed. Fixed in version 1.4.2.
