### ISSUE TITLE
when i summon a lighting it works, but when its struck by lighting, it dont work

### ISSUE THREAD

**Issue by BlahajTheShark14** [Miki-Tellurium/TurtleChargingStation#5]
maybe im too idiot for that XD (but it just dont work) (with weather2 thunderstorms)

**Comment by Miki-Tellurium** [comment]
what version are you using and on what mod loader?

**Comment by BlahajTheShark14** [comment]
1.20.1 Forge 4.2.0 TurtleCharging station 1.4.2

**Comment by BlahajTheShark14** [comment]
okay it works with the vanilla minecraft:thunder weather but why it isnt working with weather2?

**Comment by Miki-Tellurium** [comment]
What is weather2? what mod adds it?

**Comment by BlahajTheShark14** [comment]
https://www.curseforge.com/minecraft/mc-mods/weather-storms-tornadoes/files/all?page=1&pageSize=20 
this one. maybe it will work with a newer version of it (im using 2.7.7)

**Comment by BlahajTheShark14** [comment]
it doesnt :(

**Comment by BlahajTheShark14** [comment]
could you possibly solve it? (I think for some reason only vanilla lightning can be detected.) or should I write to the creator of weather2?

**Comment by Miki-Tellurium** [comment]
The mod you are using adds its own lightining bolt entity, my mod only checks for the vanilla entity so it doesn't recognize it as valid. I can add compatibility to it with an update

**Comment by BlahajTheShark14** [comment]
oh that would be awsome thanks!

**Comment by Miki-Tellurium** [comment]
I'm going to be busy on the following 3-4 days, I'm going to make an update when I have free time again.

**Comment by BlahajTheShark14** [comment]
oh okay i can wait for sure, but thanks for the quick reply too! good luck with adding compatibility!

**Comment by BlahajTheShark14** [comment]
hey do you working on the compatiblity?

**Comment by Miki-Tellurium** [comment]
Try the new version: https://modrinth.com/mod/turtle-charging-station/version/IIWxrrzi
